# Generated by Django 6.1 on 2026-08-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_monthly_aggregation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='encrypted_gemini_key',
            field=models.BinaryField(blank=True, help_text='Gemini API key, encrypted under the per-user key', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gemini_model',
            field=models.CharField(blank=True, default='', help_text='Selected Gemini model id for category suggestions', max_length=64),
        ),
    ]
