# Generated by Django 6.1 on 2026-08-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_encrypted_gemini_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gemini_pricing',
            field=models.JSONField(blank=True, help_text='Snapshot of the selected model’s listed price, taken when the user picked the model or last checked for new prices: {display_name, input_price_per_1m, output_price_per_1m, checked_at}', null=True),
        ),
    ]
