# Generated by Django 6.1 on 2026-08-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_userprofile_gemini_pricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='simulation_params',
            field=models.JSONField(blank=True, help_text='User-overridden simulation parameters; missing ones are derived', null=True),
        ),
    ]
