# Generated by Django 6.0.7 on 2026-07-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_financialaccount_ebics_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialaccount',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
