# Generated by Django 6.1 on 2026-08-14 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_financialaccount_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(help_text='Date the entry was booked')),
                ('value_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=4, help_text='Signed amount in account currency (negative = outflow)', max_digits=20)),
                ('currency', models.CharField(max_length=3)),
                ('counterparty', models.CharField(blank=True, default='', help_text='Name of the other party', max_length=255)),
                ('counterparty_account', models.CharField(blank=True, default='', help_text='IBAN/account number of the other party, if reported', max_length=64)),
                ('description', models.TextField(blank=True, default='', help_text='Remittance info / purpose text')),
                ('source', models.CharField(choices=[('camt053', 'camt.053 statement (EBICS)'), ('fints', 'FinTS/MT940 statement'), ('broker', 'Broker API'), ('manual', 'Manual Entry')], default='manual', max_length=20)),
                ('external_id', models.CharField(blank=True, default='', help_text="Bank's own reference for this entry (e.g. AcctSvcrRef)", max_length=128)),
                ('dedup_key', models.CharField(help_text='Idempotency key, unique per account', max_length=128)),
                ('raw_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.financialaccount')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-booking_date', '-id'],
                'indexes': [models.Index(fields=['account', 'booking_date'], name='transaction_account_84da59_idx'), models.Index(fields=['booking_date'], name='transaction_booking_76b1f6_idx')],
                'constraints': [models.UniqueConstraint(fields=('account', 'dedup_key'), name='uniq_transaction_dedup_per_account')],
            },
        ),
    ]
