# Generated by Django 6.1 on 2026-08-14 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='category_manual',
            field=models.BooleanField(default=False, help_text='Category was set by the user; rules must not overwrite it'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_transfer',
            field=models.BooleanField(default=False, help_text='Transfer between own accounts; excluded from spending'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='spread_months',
            field=models.PositiveSmallIntegerField(default=1, help_text='Amortize over this many months in the normalized spending view'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_manual',
            field=models.BooleanField(default=False, help_text='Transfer flag was set by the user; detection must not change it'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_peer',
            field=models.ForeignKey(blank=True, help_text='Matching opposite entry on the other own account, if identified', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='portfolio.transaction'),
        ),
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transaction_categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_text', models.CharField(help_text='Case-insensitive substring matched against counterparty and description', max_length=128)),
                ('spread_months', models.PositiveSmallIntegerField(default=1, help_text='Spread matched transactions over this many months (1 = no spread)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_rules', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='portfolio.transactioncategory')),
            ],
            options={
                'db_table': 'category_rules',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='portfolio.transactioncategory'),
        ),
        migrations.AddConstraint(
            model_name='transactioncategory',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_category_name_per_user'),
        ),
    ]
