# Generated by Django 6.1 on 2026-08-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_transaction_category_manual_transaction_is_transfer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryrule',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AddField(
            model_name='categoryrule',
            name='position',
            field=models.PositiveIntegerField(default=0, help_text='Evaluation order — the first matching rule wins'),
        ),
    ]
