# Generated by Django 6.1 on 2026-08-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_alter_categoryrule_options_categoryrule_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='source',
            field=models.CharField(choices=[('camt053', 'camt.053 statement (EBICS)'), ('fints', 'FinTS/MT940 statement'), ('broker', 'Broker API'), ('manual', 'Manual Entry'), ('csv', 'CSV import')], default='manual', max_length=20),
        ),
    ]
