# Generated by Django 6.1 on 2026-08-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_alter_transaction_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryrule',
            name='is_regex',
            field=models.BooleanField(default=False, help_text='Interpret match_text as a regular expression instead of a substring'),
        ),
        migrations.AlterField(
            model_name='categoryrule',
            name='match_text',
            field=models.CharField(help_text='Case-insensitive substring (or regex, see is_regex) matched against counterparty and description', max_length=128),
        ),
    ]
