# Generated by Django 6.1 on 2026-08-24 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_categoryrule_is_regex_alter_categoryrule_match_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryrule',
            name='is_transfer',
            field=models.BooleanField(default=False, help_text='Mark matches as transfers between own accounts instead of assigning a category (transfers never carry a category)'),
        ),
        migrations.AlterField(
            model_name='categoryrule',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Target category; NULL for transfer rules (see is_transfer)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='portfolio.transactioncategory'),
        ),
        migrations.AddConstraint(
            model_name='categoryrule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('category__isnull', True), ('is_transfer', True)), models.Q(('category__isnull', False), ('is_transfer', False)), _connector='OR'), name='rule_category_xor_transfer'),
        ),
    ]
