# Generated by Django 6.1 on 2026-08-25 21:11

import django.db.models.functions.text
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_categoryrule_is_transfer_alter_categoryrule_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactioncategory',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
    ]
