# Generated by Django 6.1 on 2026-08-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_alter_transactioncategory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactioncategory',
            name='monthly_budget',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monthly spending target in the base currency (empty = none)', max_digits=12, null=True),
        ),
    ]
