# Generated by Django 6.1 on 2026-08-28 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_transactioncategory_monthly_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryrule',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Upper bound on |amount|; NULL for no upper bound', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='categoryrule',
            name='max_inclusive',
            field=models.BooleanField(default=False, help_text='True for <= max_amount, False for < max_amount'),
        ),
        migrations.AddField(
            model_name='categoryrule',
            name='min_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Lower bound on |amount|; NULL for no lower bound', max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='categoryrule',
            name='min_inclusive',
            field=models.BooleanField(default=True, help_text='True for >= min_amount, False for > min_amount'),
        ),
    ]
