# Generated by Django 6.1 on 2026-08-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_categoryrule_max_amount_categoryrule_max_inclusive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryrule',
            name='direction',
            field=models.CharField(choices=[('any', 'Any'), ('payment', 'Payments only (amount < 0)'), ('income', 'Income only (amount > 0)')], default='any', help_text='Restrict to money out, money in, or neither', max_length=8),
        ),
    ]
